// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiseDiary.WebUI.Data;

namespace RiseDiary.WebUI.Migrations
{
    [DbContext(typeof(DiaryDbContext))]
    partial class DiaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029");

            modelBuilder.Entity("RiseDiary.Model.Cogitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CogitationDate");

                    b.Property<int>("DiaryRecordId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("DiaryRecordId");

                    b.ToTable("Cogitations");
                });

            modelBuilder.Entity("RiseDiary.Model.DiaryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<byte[]>("ImageData");

                    b.Property<string>("ImageName");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RiseDiary.Model.DiaryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("RecordCreateDate");

                    b.Property<DateTime>("RecordDate");

                    b.Property<DateTime>("RecordModifyDate");

                    b.Property<string>("RecordName");

                    b.Property<string>("RecordText");

                    b.HasKey("Id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("RiseDiary.Model.DiaryRecordImage", b =>
                {
                    b.Property<int>("DiaryRecordId");

                    b.Property<int>("DiaryImageId");

                    b.HasKey("DiaryRecordId", "DiaryImageId");

                    b.ToTable("RecordImages");
                });

            modelBuilder.Entity("RiseDiary.Model.DiaryRecordTheme", b =>
                {
                    b.Property<int>("DiaryRecordId");

                    b.Property<int>("DiaryThemeId");

                    b.HasKey("DiaryRecordId", "DiaryThemeId");

                    b.ToTable("RecordThemes");
                });

            modelBuilder.Entity("RiseDiary.Model.DiaryScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ScopeName");

                    b.HasKey("Id");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("RiseDiary.Model.DiaryTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DiaryScopeId");

                    b.Property<string>("ThemeName");

                    b.HasKey("Id");

                    b.HasIndex("DiaryScopeId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("RiseDiary.Model.Cogitation", b =>
                {
                    b.HasOne("RiseDiary.Model.DiaryRecord")
                        .WithMany("Cogitations")
                        .HasForeignKey("DiaryRecordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RiseDiary.Model.DiaryTheme", b =>
                {
                    b.HasOne("RiseDiary.Model.DiaryScope")
                        .WithMany("RecordTypes")
                        .HasForeignKey("DiaryScopeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
